#! /bin/sh


setxkbmap -option altwin:swap_lalt_lwin -layout "us, ru" -option grp:shift_caps_switch
~/.config/bspwm/tools/screenlayout.sh
~/.config/bspwm/polybar/launch.sh &
exec picom --config ~/.config/bspwm/picom/config.conf &

killall sxhkd
sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &

bspc monitor primary -d '✸' 1 2 3 4 5 6 '➤'

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc desktop -f 1

nitrogen --restore

